### ISSUE TITLE
change enemy charater

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/call-police-game#2]
replace enemy character with amg1_fr1

![image](https://user-images.githubusercontent.com/88339569/229271373-8e78de24-afd1-4e9b-b94b-675038349643.png)

You will find images in sprites folder.

**Comment by SahilDave04** [comment]
Hey!
This looks interesting. I want in.

**Comment by SahilDave04** [comment]
Tell me where to start.

**Comment by virajp4** [comment]
Hello, I can do that

**Comment by SahilDave04** [comment]
I think this issue has been resolved by me yesterday.
